---
name: Spell Check - Workflow
# Trigger the workflow on push to any branch including main
on:
  push:
jobs:
  spell-check:
    name: markdown spell check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.32.0
      name: Spellcheck
      with:
        config_path: .github/config/.spellcheck.yaml
        task_name: Markdown