---
# Action Repo: https://github.com/actions/stale

name: Mark stale issues and pull requests

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This Issue has been marked as Stale because it has been open for 7 days with no activity. Remove the Stale label or comment on the Issue, or it will be automatically closed in 7 days."
          stale-pr-message: "This PR has been marked as Stale because it has been open for 7 days with no activity. Remove the Stale label or comment on the PR, or it will be automatically closed in 7 days."
          close-issue-message: "This Issue was closed due to prolonged inactivity."
          close-pr-message: "This PR was closed due to prolonged inactivity."
          exempt-issue-labels: "awaiting-approval,work-in-progress"
          stale-issue-label: "no-issue-activity"
          stale-pr-label: "no-pr-activity"
          exempt-pr-labels: "awaiting-approval,work-in-progress"
          closed-issue-label: "closed-due-to-inactivity"
          closed-pr-label: "closed-due-to-inactivity"
          days-before-stale: 7
          days-before-close: 7
